"""supp

Revision ID: 23b5e2edd866
Revises: d024c8d38e25
Create Date: 2026-05-13 22:15:06.183648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23b5e2edd866'
down_revision = 'd024c8d38e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Visage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('visage')
    with op.batch_alter_table('salaire', schema=None) as batch_op:
        batch_op.drop_column('dept')
        batch_op.drop_column('nom_complet')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nom_complet',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('nom_complet',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('salaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_complet', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('dept', mysql.VARCHAR(length=100), nullable=True))

    op.create_table('visage',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('image', sa.BLOB(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('visage_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Visage')
    # ### end Alembic commands ###
