"""empty message

Revision ID: da1a5777df3c
Revises: 48474d524578
Create Date: 2026-05-09 23:39:46.892303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1a5777df3c'
down_revision = '48474d524578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devise', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaire', schema=None) as batch_op:
        batch_op.drop_column('devise')

    # ### end Alembic commands ###
